Typescript intellisence for vite environment variables in vue file
codex-team/notes.web pull request #123
Opened 2024-02-27 00:04 UTC by iamgabrielsoft

Typescript exposes vite environmental variables to the code for intellisence easy pickup
![Screenshot from 2024-02-27 01-03-58](https://github.com/codex-team/notes.web/assets/71671874/733c82c7-8dd1-4029-ad74-9fff76adccf6)

2024-02-27 15:46 UTC, neSpecc requested changes

2024-02-27 15:46 UTC, neSpecc commented on .env.sample
unrelated changes of env example.

2024-03-04 19:46 UTC, neSpecc approved these changes

2024-03-05 07:52 UTC, slaveeks approved these changes

2024-03-08 19:48 UTC, TatianaFomina commented
please merge

2024-03-09 07:39 UTC, merged