feat(codex-ui): row list component
codex-team/notes.web pull request #166
Opened 2024-04-06 12:54 UTC by elizachi

- FormField component was splited into two components: FormField and FormSection
- Added new component RowList

2024-04-06 14:06 UTC, TatianaFomina commented on codex-ui/src/vue/form/FormSection.vue
> +./FormSection.types
Please remove this line. It's automatically added by IDE, probably plugin bug

2024-04-06 14:14 UTC, TatianaFomina commented on codex-ui/src/vue/row/index.ts
RowList should have it's separate folder

2024-04-06 14:14 UTC, TatianaFomina commented on codex-ui/src/vue/form/index.ts
> +export { FormSection, FormField };
`FormSection` should have it's separate folder. 'form' folder should be renamed to `FormField`

2024-04-06 14:14 UTC, TatianaFomina commented on codex-ui/src/vue/form/FormSection.vue
> +// const model = defineModel();
commented out line

2024-04-06 14:14 UTC, TatianaFomina commented on codex-ui/src/vue/row/RowList.vue
> +</style>
Accourding to mockups, RowList should have background and rounded corners

![image](https://github.com/codex-team/notes.web/assets/31101125/5bbe31df-d30c-4591-ab91-1f81e2902a71)

2024-04-06 14:38 UTC, neSpecc requested changes

2024-04-06 14:38 UTC, neSpecc commented on codex-ui/src/vue/row/RowList.vue
This component seems redundant. I think, we can add the `withBackground` property. To the `FormSection` component. This property should be `true` by default (since most components will need bg), and `false` in the `FormField`

2024-04-06 14:38 UTC, neSpecc commented on codex-ui/src/vue/form/FormSection.vue
>      <div :class="$style['field-field']">
class names should be renamed as well

2024-04-06 14:38 UTC, neSpecc commented on codex-ui/src/vue/form/FormField.vue
> +     * Form section title
```suggestion
     * Form field title
```

2024-04-06 14:38 UTC, neSpecc commented on codex-ui/src/vue/form/FormField.vue
> +     * The size of the form section and input
```suggestion
     * The size of the form field and input
```

2024-04-10 11:52 UTC, neSpecc requested changes

2024-04-10 11:52 UTC, neSpecc commented on codex-ui/dev/Playground.vue
> +      with-background="false"
seems redundant

2024-04-10 11:52 UTC, neSpecc commented on codex-ui/src/vue/form-field/FormField.vue
> +    title: string;
The caption property is missing.

2024-04-10 11:52 UTC, neSpecc commented on codex-ui/dev/Playground.vue
> +    <Heading :level="3">Row List</Heading>
```suggestion
    <Heading :level="3">Form Section</Heading>
```

2024-04-10 11:52 UTC, neSpecc commented on codex-ui/dev/Playground.vue
> +const items = [
```suggestion
const formSectionItems = [
```

2024-04-10 11:52 UTC, neSpecc commented on codex-ui/src/vue/form-field/FormField.vue
> +  >
`withBackground = false` missed

2024-04-10 11:52 UTC, neSpecc commented on codex-ui/src/vue/form-section/FormSection.vue
> +    border-radius: var(--radius-m);
vertical padding is missed 
<img width="1027" alt="image" src="https://github.com/codex-team/notes.web/assets/3684889/e08a1b45-a3f3-470f-8b8e-f586d0d737d5">

2024-04-10 11:52 UTC, neSpecc commented on codex-ui/src/vue/form-field/FormField.vue
lets leave it under `form/Field.vue`, and move section to `form/Section.vue`

2024-04-10 11:52 UTC, neSpecc commented on codex-ui/src/vue/form-section/FormSection.vue
> +      background-color: #0a0a0a;
color hardcoded

2024-04-10 13:10 UTC, neSpecc commented on codex-ui/src/vue/form/Field.vue
> +  >
caption is missed

2024-04-10 13:10 UTC, neSpecc commented on codex-ui/src/vue/form/Section.vue
> +    --v-padding: var(--spacing-xs);
move `-v-padding` next to the `--h-padding` and use it here. But it should be applied only along with `withBackground=true` property

```css
&--bg {
  padding-block: var(--v-padding);
  border-radius: var(--radius-m);
  background-color: var(--base--bg-secondary);
}
```

2024-04-10 13:28 UTC, neSpecc approved these changes

2024-04-10 15:20 UTC, TatianaFomina commented on codex-ui/src/vue/form/Section.vue
> +    &--bg {
maybe call class more clear?
```suggestion
    &--with-background {
```

2024-04-10 15:37 UTC, TatianaFomina approved these changes

2024-04-10 15:40 UTC, merged