feat: add desciptions and covers
codex-team/notes.web pull request #234
Opened 2024-07-02 21:57 UTC by GeekaN2

Look at this DUDE

![image](https://github.com/codex-team/notes.web/assets/40016207/0cd7831a-2421-4ac6-89fd-0f7eb0895e60)

2024-07-03 19:26 UTC, slaveeks commented
conflict

2024-07-03 19:29 UTC, slaveeks commented on src/presentation/components/marketplace/EditorToolElement.vue
> +    :src="`http://localhost:9001/api/v1/buckets/editor-tool-covers/objects/download?preview=true&prefix=${tool.cover}&version_id=null`"
not production thing

2024-07-03 19:39 UTC, slaveeks commented on src/infrastructure/transport/notes-api/index.ts
> +  public async post<Payload, Response = Payload>(endpoint: string, data?: JSONValue | FormData, params?: NotexApiRequestParams): Promise<Response> {
![image](https://github.com/codex-team/notes.web/assets/81693471/754132fa-6bc7-40e5-9433-3cb7d9282778)

2024-07-03 19:50 UTC, GeekaN2 commented on src/presentation/components/marketplace/EditorToolElement.vue
> +    :src="`http://localhost:9001/api/v1/buckets/editor-tool-covers/objects/download?preview=true&prefix=${tool.cover}&version_id=null`"
Waiting for Nikita

2024-07-03 19:54 UTC, slaveeks approved these changes

2024-07-03 20:17 UTC, neSpecc requested changes
Home page is broken 

<img width="2539" alt="image" src="https://github.com/codex-team/notes.web/assets/3684889/4bdf4844-997a-4911-ae15-7d4724a7df11">

2024-07-03 20:21 UTC, neSpecc commented on codex-ui/src/styles/dimensions.pcss
> +  --layout-block-width: 268px;
left is 300. there are also 16 px paddings 
<img width="929" alt="image" src="https://github.com/codex-team/notes.web/assets/3684889/f033300a-a1b9-487e-9ada-0cc2d504ff58">

2024-07-03 20:21 UTC, neSpecc commented on src/presentation/pages/marketplace/MarketplacePage.vue
> +  <DefaultLayout>
Lets call it `ThreeColsLayout`

2024-07-03 20:21 UTC, neSpecc commented on src/presentation/pages/marketplace/MarketplacePage.vue
> +    <template #block-left>
```suggestion
    <template #left-col>
```

2024-07-03 20:21 UTC, neSpecc commented on src/presentation/pages/marketplace/MarketplacePage.vue
> +    <template #default>
```suggestion
    <template #center>
```

2024-07-03 20:21 UTC, neSpecc commented on src/presentation/pages/marketplace/MarketplacePage.vue
> +      <AddTool v-if="route.path === '/marketplace/add'" />
use sub routes instead

2024-07-03 20:21 UTC, neSpecc commented on src/presentation/pages/marketplace/AddTool.vue
> +async function setCover(event: Event) {
docs missed

2024-07-03 20:22 UTC, neSpecc reviewed
Paddings are different

<img width="1047" alt="image" src="https://github.com/codex-team/notes.web/assets/3684889/59c70a2e-4d79-477d-b567-fa83aea1e46d">

2024-07-03 20:27 UTC, neSpecc commented on src/infrastructure/marketplace.repository.ts
> +    const data = new FormData();
it is a transport-level staff, repo should not care about it. Move it to the transport

2024-07-03 20:27 UTC, neSpecc commented on src/presentation/pages/marketplace/AddTool.vue
>    <div class="container">
use large `dimensions`

2024-07-03 20:27 UTC, neSpecc commented on src/presentation/pages/marketplace/AddTool.vue
> +    <span class="headings">
why span?

2024-07-03 20:27 UTC, neSpecc commented on src/presentation/pages/marketplace/AddTool.vue
> +        <Section
We have Fieldset component for the `title+sections`

2024-07-03 20:27 UTC, neSpecc commented on src/presentation/pages/marketplace/AddTool.vue
> +            subtitle="A cool descriptive screenshot of the Tool's UI"
i18n missed

2024-07-03 20:27 UTC, neSpecc commented on src/presentation/pages/marketplace/AddTool.vue
> +              <Button class="add-cover-button"> Select file </Button>
i18n

2024-07-03 20:27 UTC, neSpecc commented on src/presentation/pages/marketplace/AddTool.vue
> +  function arrayBufferToBase64(buffer: ArrayBuffer) {
move to `infrastructure/utils/buffer`

2024-07-03 22:07 UTC, neSpecc commented on src/domain/noteList.service.ts
> +        console.log('bonka', note?.id, note.cover);
```suggestion
```

2024-07-03 22:07 UTC, neSpecc commented on src/infrastructure/transport/types/FileDto.ts
> +  fileName: string;
add docs

2024-07-03 22:07 UTC, neSpecc commented on src/infrastructure/transport/notes-api/index.ts
> +    if (files) {
move to fetch transport

2024-07-03 22:07 UTC, neSpecc commented on src/infrastructure/transport/notes-api/index.ts
> +      const multipartFormData = new FormData();
create util `composeFormDataFromFilesDto()`

2024-07-04 14:31 UTC, neSpecc commented on src/application/router/routes.ts
> +      name: 'marketplace',
```suggestion
      name: 'marketplaceTools',
```

2024-07-04 14:31 UTC, neSpecc commented on src/application/router/routes.ts
> +      name: 'newTool',
```suggestion
      name: 'marketplaceAddTool',
```

2024-07-04 14:31 UTC, neSpecc commented on src/infrastructure/transport/fetch.transport.ts
> +  }): Promise<JSONValue> {
move this object to types

2024-07-04 14:31 UTC, neSpecc commented on src/infrastructure/transport/fetch.transport.ts
> +      body = composeFormDatFromFilesDto(payload, files);
```suggestion
      body = composeFormDataFromFilesDto(payload, files);
```

2024-07-04 14:31 UTC, neSpecc commented on src/infrastructure/transport/utils/composeFormDataFromFilesDto.ts
> +export const composeFormDatFromFilesDto = (payload: Record<string, JSONValue | undefined> | undefined, files: FilesDto): FormData => {
add cool docs please

2024-07-04 14:31 UTC, neSpecc commented on src/infrastructure/utils/buffer.ts
> +export const arrayBufferToBase64 = (buffer: ArrayBuffer): string => {
add simple docs

2024-07-04 15:22 UTC, merged