refactor(codex-ui):search in context menu
codex-team/notes.web pull request #235
Opened 2024-07-02 22:45 UTC by elizachi

It is now possible to search for an item among menu context items

![image](https://github.com/codex-team/notes.web/assets/94054053/27f45d2b-2a30-43cd-b3cc-3a5232caef70)
![image](https://github.com/codex-team/notes.web/assets/94054053/96f527cf-22e4-4b91-8a00-69a5c48643d1)

2024-07-03 00:15 UTC, slaveeks commented on codex-ui/dev/pages/components/ContextMenu.vue
> +    :message="'Nothing found'"
```suggestion
    message="Nothing found"
```

2024-07-03 00:20 UTC, slaveeks commented on codex-ui/src/vue/components/context-menu/ContextMenu.vue
> +  return searchedItems;
add some docs to this logic please

2024-07-03 00:23 UTC, neSpecc commented on codex-ui/dev/pages/components/ContextMenu.vue
> +    :message="'Nothing found'"
unclear property name

2024-07-03 00:23 UTC, neSpecc commented on codex-ui/dev/pages/components/ContextMenu.vue
> +    :message="'Nothing found'"
I think we can get rid of it at all since it is a static text, you can pass it inside the ContextMenu to item

2024-07-03 00:30 UTC, e11sy commented
![image](https://github.com/codex-team/notes.web/assets/130844513/86008942-9b24-41c7-aed9-2ae656c4ffca)
last separator should be removed also

2024-07-03 00:37 UTC, e11sy requested changes

2024-07-03 00:37 UTC, e11sy commented on codex-ui/dev/pages/components/ContextMenu.vue
> +    :message="'Nothing found'"
use i18n

2024-07-03 00:37 UTC, e11sy commented on codex-ui/src/vue/components/context-menu/ContextMenu.vue
> +    message: string;
i think that is we use it just for search, it should be moved to constants as "Nothing found" or smth same

2024-07-03 00:37 UTC, e11sy commented on codex-ui/src/vue/components/context-menu/ContextMenu.vue
> +    } else if (item.type === 'separator') {
remove this and check (*) comment

2024-07-03 00:37 UTC, e11sy commented on codex-ui/src/vue/components/context-menu/ContextMenu.vue
> +      </template>
(*) comment:
if we do not filter items with type: message, we will have two cases
- items are only with type message element
```
{ type: 'message'}
``` 
- some items without type message

2024-07-03 00:37 UTC, e11sy commented on codex-ui/src/vue/components/context-menu/ContextMenu.vue
> +  return searchedItems;
(*) we have this case only when `serchedItems.lenght === 0`, so we can just return message item here

2024-07-03 13:50 UTC, e11sy commented on codex-ui/src/vue/components/context-menu/ContextMenu.vue
> +      items = items.slice(0, items.length - 1);
this is pop()

2024-07-04 14:27 UTC, e11sy approved these changes

2024-07-04 16:39 UTC, kloV148 approved these changes

2024-07-04 17:08 UTC, merged