[Feature] Implement Checkbox Component for Codex-UI (#272)
codex-team/notes.web pull request #274
Opened 2024-11-03 20:15 UTC by Dobrunia

### Problem
This PR implements the checkbox component for the Codex-UI as described in Issue #272.

### Solution
- Created a new Checkbox component following the design provided in Figma.
- Added the component to `/codex-ui/src/vue/components`.
- Developed a demonstration page for the component in `/codex-ui/dev/pages`.
- Configured various states for the checkbox component (checked, unchecked, hover, disabled) according to the design specifications.
- Applied styles to match the Figma design.

### Additional Information
This component includes multiple states, such as `hover`, `disabled`, `checked`, and `unchecked`, all controlled via props for maximum flexibility.

2024-11-04 15:36 UTC, e11sy requested changes

2024-11-04 15:36 UTC, e11sy commented on codex-ui/src/vue/components/checkbox/Checkbox.vue
> +    @mouseleave="setHover(false)"
you should use postcss :hover pseudoclass

2024-11-04 15:36 UTC, e11sy commented on codex-ui/src/vue/components/checkbox/Checkbox.vue
> +  height: 20px;
use css variables from `dimensions.pcss`

2024-11-04 15:36 UTC, e11sy commented on codex-ui/src/vue/components/checkbox/Checkbox.vue
> +}
it's better to use postcss nested ancestors (like `&__icon`  etc)

2024-11-04 15:37 UTC, e11sy commented
also attach an issue [correctly](https://docs.github.com/ru/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue)

2024-11-13 10:51 UTC, neSpecc commented on codex-ui/src/vue/components/checkbox/Checkbox.vue
> +    <div class="checkbox__icon">
seems like a redundant wrapper

2024-11-13 10:51 UTC, neSpecc commented on codex-ui/src/vue/components/checkbox/Checkbox.vue
> +    transform: translate(-50%, -50%);
I think, `absolute` position is redundant here. It can be centered by `flex` on parent

2024-11-13 14:35 UTC, neSpecc commented on codex-ui/src/vue/components/checkbox/Checkbox.vue
> +/* Define component props with default values */
```suggestion
/**
 * Define component props with default values 
 */
```

2024-11-13 14:35 UTC, neSpecc commented on codex-ui/src/vue/components/checkbox/Checkbox.vue
> +    disabled?: boolean;
docs

2024-11-13 14:49 UTC, neSpecc approved these changes

2024-11-13 17:26 UTC, e11sy commented on codex-ui/src/vue/components/checkbox/Checkbox.vue
> +
maybe we can use `pointer-events: none` and get rid of `:not(.checkbox--disabled)`  for :hover pseudoclasses?

2024-11-19 16:48 UTC, e11sy approved these changes

2024-11-19 22:18 UTC, merged