[Feature] Dropdown component for Codex UI
codex-team/notes.web pull request #279
Opened 2024-11-28 20:55 UTC by DeadCreator

Added Dropdown component implementation (#273), but in component only one option is selectable. Also updated icons package version in package json's

2024-11-28 21:10 UTC, neSpecc commented on codex-ui/src/vue/components/dropdown/Dropdown.vue
> +    <div :style="showPopover ? {'display' : 'block'} : {'display': 'none'}">
use the Popover component as a wrapper

2024-11-28 22:00 UTC, e11sy commented
why file in `dev/pages` is called `Select.vue` if component name is dropdown...

2024-12-03 18:10 UTC, e11sy requested changes

2024-12-03 18:10 UTC, e11sy commented on codex-ui/src/vue/components/dropdown/Dropdown.vue
> +    activeItem.value.onActivate = console.log;
also this works wrong

this works wrong:

- If i open popover by pressing dropdown button, then isOpened becomes `true`
- Then i select any option in context menu, popover becomes hidden, and title of the button updates
- If i press popover button one more time it makes isOpened `false` and nothing changes on page (i expect popover to be opened again)

so we should manually `hide()` popover, when new item selected or popover closed by pressing anywhere else

2024-12-12 16:55 UTC, e11sy commented
can't see the icon of the select
![image](https://github.com/user-attachments/assets/c8b571c2-69d1-4a7b-8cfa-f1e69ef743e6)

2024-12-12 16:55 UTC, e11sy commented on codex-ui/dev/pages/components/Select.vue
> +    Dropdown
now it is select

2024-12-12 17:06 UTC, DeadCreator commented
Strange, locally everything is fine...Maybe the reason is that the icon was recently added to icons pack

2024-12-12 21:33 UTC, neSpecc commented on codex-ui/dev/pages/components/Select.vue
> +  },
too many separators, lets leave just one

2024-12-12 21:33 UTC, neSpecc commented on codex-ui/src/vue/components/select/Select.vue
> +    @click="!isOpen ? togglePopover($event.currentTarget, {vertically: 'below', horizontally: 'left'}) : hide()"
`toggle` means that it includes hide internally. So I would suggest to move `isOpen` check inside it.

2024-12-12 21:33 UTC, neSpecc commented on codex-ui/src/vue/components/select/Select.vue
> +  title: 'Choose an option',
should be customizable via prop

2024-12-12 21:33 UTC, neSpecc commented on codex-ui/src/vue/components/select/Select.vue
> +  if (item.type === 'default' || !item.type) {
this check is being repeated several times, os it can be utilized

2024-12-12 21:33 UTC, neSpecc commented on codex-ui/src/vue/components/select/Select.vue
> +    activeItem.value = Object.create(item);
why Object.create is used?

2024-12-14 12:23 UTC, neSpecc commented on codex-ui/src/vue/components/select/Select.vue
> +      align,
lets also pass `width: 'fit-target'` property to make popover width same as  a button width

2024-12-14 12:24 UTC, neSpecc approved these changes

2024-12-15 14:12 UTC, e11sy approved these changes

2024-12-16 20:28 UTC, merged