Add i18n & router
codex-team/notes.web pull request #5
Opened 2023-06-12 12:01 UTC by HyTekCoop

Add i18n & router and also delete empty files

2023-06-12 14:46 UTC, neSpecc reviewed
seems like i18 and router are not connected to the `src/index.ts`

2023-06-12 14:46 UTC, neSpecc commented on src/application/router/router.ts
lets call the file `index.ts`

2023-06-14 07:37 UTC, slaveeks commented on src/application/i18n/index.ts
> +Vue.use(VueI18n);
I think, you need to call it in `index.ts` file

2023-06-19 18:40 UTC, neSpecc requested changes

2023-06-23 05:31 UTC, HyTekCoop commented on src/application/router/index.ts
> +      redirect: '/app',
changes added

2023-06-23 11:35 UTC, neSpecc approved these changes

2023-06-23 11:37 UTC, slaveeks approved these changes

2023-06-24 09:43 UTC, merged