feat: show editor tools in user settings
codex-team/notes.web pull request #67
Opened 2023-10-21 21:38 UTC by GeekaN2

Show list of user editor tools. 
Without default ones yet

<img width="986" alt="image" src="https://github.com/codex-team/notes.web/assets/40016207/6a4a8352-c8db-4b0d-93e7-f196b028c292">

2023-10-21 21:44 UTC, neSpecc commented on src/infrastructure/storage/user.ts
> +
docs missed

2023-10-21 21:44 UTC, neSpecc commented on src/infrastructure/storage/user.ts
> +   *
nasty docs

2023-10-21 21:44 UTC, neSpecc commented on src/application/services/useAppState.ts
> +  userEditorTools: Ref<EditorTool[]>
document please

2023-10-21 21:44 UTC, neSpecc commented on src/domain/user.repository.interface.ts
> +  getUserEditorTools: () => EditorTool[];
docs pls

2023-10-21 21:44 UTC, neSpecc commented on src/domain/entities/EditorTool.ts
> +  class: string;
bad naming

2023-10-21 23:07 UTC, neSpecc requested changes
Comments ignored

2023-10-21 23:26 UTC, neSpecc approved these changes

2023-10-31 13:15 UTC, slaveeks approved these changes

2023-11-07 10:11 UTC, merged